name: Arena
version: '${project.version}'
main: arena.MainArena
api-version: 1.18

commands:
  +dvere:
  +obchodnikJidlo:
  +obchodnikZbrane:
  +mecNaObchodnika:
  +monsterSwitch:
  +resetMonsterSwitch:
  +znicMonstra:
  +resetHry:

